[package]
name = "backlog-service"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.30"
backlog-repo = { path = "../../driven/backlog-repo" }
backlog = { path = "../../../cores/backlog" }
eyre-ext = { path = "../../../utils/eyre-ext" }
async-trait = "0.1.52"
anyhow = "1.0.52"
eyre = "0.6.5"

[dev-dependencies]
jsonpath-rust = "0.1.4"
mockall = "0.11.0"
serde = "1.0.133"
serde_json = "1.0.74"
tokio = { version = "1.15.0", features = ["macros", "rt-multi-thread"] }

